targets: 
  $default:
    builders: 
      json_serializable:
        options: 
          explicit_to_json: true
          field_rename: kebab 



# targets: 
#   $default:
#     builders: 
#       json_serializable:
#         options: 
#           any_map: false
#           checked: false #CheckedFromJsonException
#           constructor: ""
#           create_factory: true
#           create_to_json: true
#           disallow_unrecognized_keys: false #UnrecognizedKeysException
#           explicit_to_json: true

#           #camelCase, kebab, snake, none, pascal
#           field_rename: kebab 
#           generic_argument_factories: false 
#           ignore_unannotated: false 
#           include_if_null: true 
